FROM python:3.8-slim

EXPOSE 5000

RUN apt-get -y update
RUN apt-get install -y \
    gcc \
    python3-dev \
    libpq-dev

RUN pip install pipenv
RUN cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
RUN echo "America/Sao_Paulo" >  /etc/timezone

ENV TZ America/Sao_Paulo
ENV LANG pt_BR.UTF-8
ENV LANGUAGE pt_BR.UTF-8
ENV LC_ALL pt_BR.UTF-8

RUN set -ex && mkdir -p /opt/app
WORKDIR /opt

COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock

RUN pipenv install --dev --system --verbose

COPY . .

CMD ["/bin/sh"]
