"""empty message

Revision ID: 030b53250bd4
Revises: 2fe1f0a57271
Create Date: 2021-09-16 16:35:06.738653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "030b53250bd4"
down_revision = "2fe1f0a57271"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("verified", sa.Boolean(), nullable=True, server_default="true"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "verified")
    # ### end Alembic commands ###
