"""empty message

Revision ID: 0583330bfa51
Revises: 24da3e3e340a
Create Date: 2021-03-25 16:28:26.202822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0583330bfa51"
down_revision = "24da3e3e340a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "surname")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "surname", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
