"""empty message

Revision ID: 15b8e046cb96
Revises: f09f1c10a73d
Create Date: 2022-03-03 12:28:08.888238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "15b8e046cb96"
down_revision = "f09f1c10a73d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column("stripe_company_email", sa.String(length=255), nullable=True),
    )
    op.add_column("user", sa.Column("is_financial", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_financial")
    op.drop_column("company", "stripe_company_email")
    # ### end Alembic commands ###
