"""empty message

Revision ID: 1ed5c2fb700a
Revises: 14e43b7836f9
Create Date: 2022-06-13 12:24:13.786185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1ed5c2fb700a"
down_revision = "14e43b7836f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "internal_database_title_key", "internal_database", type_="unique"
    )
    op.create_unique_constraint(None, "internal_database", ["title", "company_id"])
    op.drop_constraint("tag_title_key", "tag", type_="unique")
    op.create_unique_constraint(None, "tag", ["title", "company_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tag", type_="unique")
    op.create_unique_constraint("tag_title_key", "tag", ["title"])
    op.drop_constraint(None, "internal_database", type_="unique")
    op.create_unique_constraint(
        "internal_database_title_key", "internal_database", ["title"]
    )
    # ### end Alembic commands ###
