"""empty message

Revision ID: 24da3e3e340a
Revises: 32ba0eadf92b
Create Date: 2021-03-17 13:04:14.084134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24da3e3e340a'
down_revision = '32ba0eadf92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'logo_url')
    op.add_column('document_template', sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_template', 'variables')
    op.add_column('company', sa.Column('logo_url', sa.VARCHAR(length=1500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
