"""empty message

Revision ID: 26d02b4ddbf0
Revises: 030b53250bd4
Create Date: 2021-09-21 11:20:17.846939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d02b4ddbf0'
down_revision = '030b53250bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'due_date')
    # ### end Alembic commands ###
