"""empty message

Revision ID: 2c9d912b031c
Revises: 8059b551b714
Create Date: 2020-05-11 22:26:47.379852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c9d912b031c"
down_revision = "8059b551b714"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_title", "document", ["title"])
    op.add_column(
        "user",
        sa.Column("docusign_refresh_token", sa.String(length=700), nullable=True),
    )
    op.add_column(
        "user", sa.Column("docusign_token", sa.String(length=700), nullable=True)
    )
    op.add_column(
        "user", sa.Column("docusign_token_obtain_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "docusign_token_obtain_date")
    op.drop_column("user", "docusign_token")
    op.drop_column("user", "docusign_refresh_token")
    op.drop_constraint("unique_title", "document", type_="unique")
    # ### end Alembic commands ###
