"""empty message

Revision ID: 315100610499
Revises: 37783b788108
Create Date: 2020-10-01 12:31:56.323132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315100610499'
down_revision = '37783b788108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('company_id', sa.Integer(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('participates_on',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_constraint('user_user_group_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'user_group_id')
    op.drop_table('user_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_group_id',
                                    sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_user_group_id_fkey', 'user',
                          'user_group', ['user_group_id'], ['id'])
    op.create_table('user_group',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=True),
                    sa.Column('company_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('active', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['company.id'], name='user_group_company_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='user_group_pkey')
                    )
    op.drop_table('participates_on')
    op.drop_table('group')
    # ### end Alembic commands ###
