"""empty message

Revision ID: 32ba0eadf92b
Revises: f60fc48fccaf
Create Date: 2021-03-12 13:07:59.184745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32ba0eadf92b"
down_revision = "f60fc48fccaf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document", sa.Column("text_type", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "document_template", sa.Column("filename", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "document_template",
        sa.Column("text_type", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_template", "text_type")
    op.drop_column("document_template", "filename")
    op.drop_column("document", "text_type")
    # ### end Alembic commands ###
