"""empty message

Revision ID: 382cb1f60aa7
Revises: e538803ddb41
Create Date: 2020-12-30 14:19:11.458675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382cb1f60aa7'
down_revision = 'e538803ddb41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_group', 'group', ['name', 'company_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_group', 'group', type_='unique')
    # ### end Alembic commands ###
