"""empty message

Revision ID: 38f330e70544
Revises: 0e554cb3519a
Create Date: 2021-02-18 11:37:04.177522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "38f330e70544"
down_revision = "0e554cb3519a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company", sa.Column("logo_url", sa.String(length=1500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "logo_url")
    # ### end Alembic commands ###
