"""empty message

Revision ID: 39715b7ba409
Revises: 477e46680bd6
Create Date: 2020-10-20 15:54:51.483060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "39715b7ba409"
down_revision = "477e46680bd6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document", sa.Column("current_step", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "document",
        sa.Column("signers", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "document",
        sa.Column("variables", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "document",
        sa.Column("workflow", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "workflow")
    op.drop_column("document", "variables")
    op.drop_column("document", "signers")
    op.drop_column("document", "current_step")
    # ### end Alembic commands ###
