"""Document template fk can be null

Revision ID: 473382a30175
Revises: 940bffb240bb
Create Date: 2021-06-23 15:17:09.642346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "473382a30175"
down_revision = "940bffb240bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "company", ["name"])
    op.alter_column(
        "document", "document_template_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "document", "document_template_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
