"""empty message

Revision ID: 477e46680bd6
Revises: 315100610499
Create Date: 2020-10-21 15:00:30.787768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "477e46680bd6"
down_revision = "315100610499"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_template",
        sa.Column("form", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "document_template",
        sa.Column("signers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "document_template", sa.Column("textfile", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "document_template",
        sa.Column("workflow", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_column("document_template", "filename")
    op.drop_constraint("unique_group", "group", type_="unique")
    op.drop_constraint("unique_participates_on", "participates_on", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_participates_on", "participates_on", ["group_id", "user_id"]
    )
    op.create_unique_constraint("unique_group", "group", ["name", "company_id"])
    op.add_column(
        "document_template",
        sa.Column(
            "filename", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("document_template", "workflow")
    op.drop_column("document_template", "textfile")
    op.drop_column("document_template", "signers")
    op.drop_column("document_template", "form")
    # ### end Alembic commands ###
