"""empty message

Revision ID: 4ed7a9eb6cbb
Revises: f4439648293b
Create Date: 2022-05-03 17:15:22.400905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4ed7a9eb6cbb"
down_revision = "f4439648293b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("deleted", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "document_template",
        sa.Column("deleted", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_template", "deleted")
    op.drop_column("document", "deleted")
    # ### end Alembic commands ###
