"""empty message

Revision ID: 4ef1e8ce8c7f
Revises: 2459c36eb131
Create Date: 2020-09-10 22:32:29.491610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4ef1e8ce8c7f"
down_revision = "2459c36eb131"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("username", sa.String(length=255), nullable=False))
    op.add_column("user", sa.Column("active", sa.Boolean(), nullable=True))
    op.drop_index("ik_sub", table_name="user")
    op.create_unique_constraint(None, "user", ["sub"])
    op.create_unique_constraint(None, "user", ["username"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "user", type_="unique")
    op.create_index("ik_sub", "user", ["sub"], unique=True)
    op.drop_column("user", "active")
    op.drop_column("user", "username")
    # ### end Alembic commands ###
