"""empty message

Revision ID: 5aba0b60f323
Revises: 26d02b4ddbf0
Create Date: 2021-09-17 09:42:40.316548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aba0b60f323'
down_revision = '26d02b4ddbf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_token', sa.Column('current_uses', sa.Integer(), server_default='0', nullable=False))
    op.add_column('external_token', sa.Column('max_uses', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_token', 'max_uses')
    op.drop_column('external_token', 'current_uses')
    # ### end Alembic commands ###
