"""create base_document

Revision ID: 68a324778ec1
Revises: 192f329113f9
Create Date: 2023-01-06 10:10:37.474537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68a324778ec1"
down_revision = "192f329113f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column(
            "base_document", sa.String(length=255), server_default="", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "base_document")
    # ### end Alembic commands ###
