"""empty message

Revision ID: 87dfe902a760
Revises: 15b8e046cb96
Create Date: 2022-03-16 11:34:57.809090

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Boolean
from sqlalchemy.sql import table, column
from sqlalchemy.orm.session import Session
from sqlalchemy.ext.automap import automap_base

Base = automap_base()

# revision identifiers, used by Alembic.
revision = "87dfe902a760"
down_revision = "15b8e046cb96"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column(
            "remaining_documents", sa.Integer(), server_default="20", nullable=False
        ),
    )
    op.alter_column(
        "user",
        "is_financial",
        existing_type=sa.BOOLEAN(),
        server_default="false",
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "is_financial", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("company", "remaining_documents")
    # ### end Alembic commands ###
