"""empty message

Revision ID: 8c73256c0bfc
Revises: 4ed7a9eb6cbb
Create Date: 2022-05-04 14:31:51.967395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c73256c0bfc"
down_revision = "4ed7a9eb6cbb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "document_template", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_template", "deleted_at")
    op.drop_column("document", "deleted_at")
    # ### end Alembic commands ###
