"""empty message

Revision ID: 91f564532d92
Revises: 2c9d912b031c
Create Date: 2020-05-13 13:30:04.575740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91f564532d92'
down_revision = '2c9d912b031c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('envelope', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'envelope')
    # ### end Alembic commands ###
