"""empty message

Revision ID: 940bffb240bb
Revises: cdd5d228480a
Create Date: 2021-05-28 16:07:56.864944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "940bffb240bb"
down_revision = "cdd5d228480a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("is_folder", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("document", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "parent_folder_fk", "document", "document", ["parent_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("parent_folder_fk", "document", type_="foreignkey")
    op.drop_column("document", "parent_id")
    op.drop_column("document", "is_folder")
    # ### end Alembic commands ###
