"""empty message

Revision ID: a23f2402d690
Revises: 8c73256c0bfc
Create Date: 2022-05-23 15:29:27.862273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a23f2402d690"
down_revision = "8c73256c0bfc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("draft", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document", "draft")
    # ### end Alembic commands ###
