"""empty message

Revision ID: a86af9559066
Revises: 075253f0ded6
Create Date: 2020-11-17 14:55:48.109666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a86af9559066"
down_revision = "075253f0ded6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column("docusign_account_id", sa.String(length=1500), nullable=True),
    )
    op.add_column(
        "company",
        sa.Column("docusign_integration_key", sa.String(length=1500), nullable=True),
    )
    op.add_column(
        "company",
        sa.Column("docusign_secret_key", sa.String(length=1500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "docusign_secret_key")
    op.drop_column("company", "docusign_integration_key")
    op.drop_column("company", "docusign_account_id")
    # ### end Alembic commands ###
