"""empty message

Revision ID: b0892bdb8b8e
Revises: 91f564532d92
Create Date: 2020-06-06 22:53:47.838646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b0892bdb8b8e"
down_revision = "91f564532d92"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    template_file_type = postgresql.ENUM("docx", "pdf", name="template_file_type")
    template_file_type.create(op.get_bind())
    op.alter_column(
        "document", "title", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.add_column(
        "document_template",
        sa.Column(
            "filetype",
            postgresql.ENUM("docx", "pdf", name="template_file_type"),
            nullable=True,
        ),
    )
    op.execute("UPDATE document_template SET filetype = 'docx'")
    op.alter_column("document_template", "filetype", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_template", "filetype")
    op.alter_column(
        "document", "title", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    template_file_type = postgresql.ENUM("docx", "pdf", name="template_file_type")
    template_file_type.drop(op.get_bind())
    # ### end Alembic commands ###
