"""Company D4Sign Info

Revision ID: f09f1c10a73d
Revises: 9f9f07ead72e
Create Date: 2021-09-23 17:40:17.961710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09f1c10a73d'
down_revision = '9f9f07ead72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('d4sign_api_cryptkey', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('d4sign_api_hmac_secret', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('d4sign_api_token', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('d4sign_safe_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'd4sign_safe_name')
    op.drop_column('company', 'd4sign_api_token')
    op.drop_column('company', 'd4sign_api_hmac_secret')
    op.drop_column('company', 'd4sign_api_cryptkey')
    # ### end Alembic commands ###
