"""empty message

Revision ID: f4439648293b
Revises: 48bd5f3b9c25
Create Date: 2022-04-07 11:27:13.885235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f4439648293b"
down_revision = "48bd5f3b9c25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_template", sa.Column("favorite", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_template", "favorite")
    # ### end Alembic commands ###
