"""Add signatures_provider field to Company model

Revision ID: f5a3ff33bc0f
Revises: 5aba0b60f323
Create Date: 2021-09-06 20:56:29.671313

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = "f5a3ff33bc0f"
down_revision = "5aba0b60f323"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company",
        sa.Column(
            "signatures_provider",
            app.models.fields.StringChoiceField(choices=["docusign", "d4sign"]),
            server_default="docusign",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "signatures_provider")
    # ### end Alembic commands ###
