"""empty message

Revision ID: f60fc48fccaf
Revises: b984a009fc18
Create Date: 2021-03-03 16:02:20.811934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f60fc48fccaf"
down_revision = "b984a009fc18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "external_token", sa.Column("title", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("external_token", "title")
    # ### end Alembic commands ###
