"""empty message

Revision ID: f7bbbedd6b47
Revises: a86af9559066
Create Date: 2020-12-02 17:22:16.912497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7bbbedd6b47'
down_revision = 'a86af9559066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'sent')
    # ### end Alembic commands ###
