"""Adds document version

Revision ID: 564c20b79909
Revises: 637c38bb948c
Create Date: 2020-04-24 23:08:47.396480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564c20b79909'
down_revision = '637c38bb948c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'title')
    # ### end Alembic commands ###
