"""empty message

Revision ID: f4d0e55e7581
Revises: b0892bdb8b8e
Create Date: 2020-06-30 23:45:01.566408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d0e55e7581'
down_revision = 'b0892bdb8b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_title', 'document', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_title', 'document', ['title'])
    # ### end Alembic commands ###
